# Generated by Django 3.2.4 on 2021-08-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographic',
            name='zip',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demographic',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
